apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: celery
  name: celery-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: celery
    spec:
      containers:
      - name: celery-worker
        image: shuklaabhishek/k8-sample-flask-celery:latest 
        command: ['celery', 'worker', '-l', 'DEBUG', '--config', 'katana.celeryconfig', '-Q', 'celery,low-priority']
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 100m
        env:
        - name: DATABASE_USER
          value: ms
        - name: DATABASE_PASSWORD
          value: ms
        - name: BROKER_URL
          value: amqp://guest:guest@rabbitmq-service:5672
        - name: RESULT_BACKEND_URL
          value: redis://redis-master:6379/1

